### ISSUE TITLE
Fatal IDE Error NoClassDefFoundError

### ISSUE THREAD

**Issue by robert-wallis** [RoboPlugins/git-pair.idea#7]
> gitpair.GitPairProjectComponent@43496793: java/nio/file/Paths
> java.lang.NoClassDefFoundError: java/nio/file/Paths
>       at gitpair.ui.GitPairWidget.updateState(GitPairWidget.java:65)
>       at gitpair.GitPairProjectComponent.projectOpened(GitPairProjectComponent.java:45)
>       at com.intellij.openapi.project.impl.ProjectImpl.projectOpened(ProjectImpl.java:385)
>       at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:73)
>       at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:420)
>       at com.intellij.openapi.project.impl.ProjectManagerImpl$3.projectOpened(ProjectManagerImpl.java:154)
>       at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:938)
>       at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:461)
>       at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:562)
>       at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:182)
>       at com.intellij.ide.RecentProjectsManagerImpl.doOpenProject(RecentProjectsManagerImpl.java:46)
>       at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:357)
>       at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:384)
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>       at java.lang.reflect.Method.invoke(Method.java:597)
>       at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
>       at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:322)
>       at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:309)
>       at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:288)
>       at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
>       at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
>       at com.sun.proxy.$Proxy55.appStarting(Unknown Source)
>       at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:328)
>       at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
>       at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
>       at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
>       at java.awt.EventQueue.access$400(EventQueue.java:82)
>       at java.awt.EventQueue$2.run(EventQueue.java:676)
>       at java.awt.EventQueue$2.run(EventQueue.java:674)
>       at java.security.AccessController.doPrivileged(Native Method)
>       at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
>       at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
>       at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
>       at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
>       at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
>       at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
>       at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
>       at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
>       at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
>       at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
>       at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
> Caused by: java.lang.ClassNotFoundException: java.nio.file.Paths PluginClassLoader[com.smilingrob.gitpair, 1.1]
>       at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
>       ... 43 more

**Comment by robert-wallis** [comment]
Fixed by removing Files and Path classes, and instead using a BufferReader
